//  Light uniform parameters.

#ifdef ENABLE_DIRECTIONAL_LIGHT_SPILL_OVER_FACTOR
#define NU_LIGHT_PARAMETERS_DIRECTIONAL 7
#else
#define NU_LIGHT_PARAMETERS_DIRECTIONAL 6
#endif
#define NU_LIGHT_PARAMETERS_POINT_SOURCE 7
#define NU_LIGHT_PARAMETERS_SPOT 11
#define NU_LIGHT_PARAMETERS_BEAM 13
#define NU_LIGHT_PARAMETERS_LOCAL 15
#define NU_LIGHT_PARAMETERS_MAX 16

#define LIGHT_POSITION_X 0
#define LIGHT_POSITION_Y 1
#define LIGHT_POSITION_Z 2
#define LIGHT_COLOR_R 3
#define LIGHT_COLOR_G 4
#define LIGHT_COLOR_B 5
#define LIGHT_LINEAR_ATTENUATION_RANGE 6
#define LIGHT_AXIS_DIRECTION_X 7
#define LIGHT_AXIS_DIRECTION_Y 8
#define LIGHT_AXIS_DIRECTION_Z 9

#define DIRECTIONAL_LIGHT_SPILL_OVER_FACTOR 6

#define SPOT_LIGHT_EXPONENT 10

#define BEAM_LIGHT_AXIS_CUT_OFF_DISTANCE 10
#define BEAM_LIGHT_RADIUS 11
#define BEAM_LIGHT_RADIAL_LINEAR_ATTENUATION_RANGE 12

#define LOCAL_LIGHT_TYPE 10
#define LOCAL_LIGHT_SPOT_EXPONENT 11
#define LOCAL_LIGHT_BEAM_AXIS_CUT_OFF_DISTANCE 12
#define LOCAL_LIGHT_BEAM_RADIUS 13
#define LOCAL_LIGHT_BEAM_RADIAL_LINEAR_ATTENUATION_RANGE 14

